### ISSUE TITLE
[Bug] 에러 로그 페이지 상단 title 미표시

### ISSUE THREAD

**Issue by gaon12** [Team-AIpaca/AIpaca_App#7]
## 어떤 버그인가요?

에러 로그 페이지 상단에 있는 title 바에 있는 title이 보이지 않습니다.

## 어떤 상황에서 발생한 버그인가요?

에러 로그 페이지에 들어가면 됩니다.

## 예상 결과

title 바에 title이 보여야 합니다.

## 참고할만한 자료(선택)
![image](https://github.com/Team-AIpaca/AIpaca_App/assets/34927797/3d7a5d17-443a-4f2c-b0e0-ab16628209a6)
![image](https://github.com/Team-AIpaca/AIpaca_App/assets/34927797/33843935-e002-45d0-853c-159145180532)

**Comment by hihotz** [comment]
해결되었습니다
