### ISSUE TITLE
[Enhancement] 에러 로그 페이지 명칭 변경 및 각 상태별 박스 색상 변경

### ISSUE THREAD

**Issue by gaon12** [Team-AIpaca/AIpaca_App#8]
## 어떤 기능인가요?

> 에러 로그 페이지 보다는 '로그' 페이지로 명칭을 바꾸고, 모든 로그를 출력되게 하면 좋을 것 같습니다.

또한 성공/실패 등을 박스 색상을 나누어 출력하면 한눈에 보기 쉬울 것 같습니다.

마지막으로 박스를 길게 누르면 클립보드에 복사가 되어 쉽게 버그를 제보할 수 있을 것 같습니다.

## 작업 상세 내용

- [x] 명칭 변경
- [x] 성공/실패 등을 박스 색상 나누어 출력
- [x] 박스 롱클릭 시 클립보드 복사

## 참고할만한 자료(선택)
![image](https://github.com/Team-AIpaca/AIpaca_App/assets/34927797/57bd7179-1c75-493f-9d01-63532738b483)

**Comment by hihotz** [comment]
2.1.4 버전 업데이트로 해결되었습니다
